module.exports = [
  'Wisconsin, USA',
  'Alaska, USA',
  'Alabama, USA',
  'Arkansas, USA',
  'Arizona, USA',
  'California, USA',
  'Colorado, USA',
  'Connecticut, USA',
  'District of Columbia, USA',
  'Delaware, USA',
  'Florida, USA',
  'Georgia, USA',
  'Hawaii, USA',
  'Iowa, USA',
  'Idaho, USA',
  'Illinois, USA',
  'Indiana, USA',
  'Kansas, USA',
  'Kentucky, USA',
  'Louisiana, USA',
  'Massachusetts, USA',
  'Maryland, USA',
  'Maine, USA',
  'Michigan, USA',
  'Minnesota, USA',
  'Missouri, USA',
  'Mississipi, USA',
  'Montana, USA',
  'North Carolina, USA',
  'North Dakota, USA',
  'Nebraska, USA',
  'New Hamphshire, USA',
  'New Jersey, USA',
  'New Mexico, USA',
  'Nevada, USA',
  'New York, USA',
  'Ohio, USA',
  'Oklahoma, USA',
  'Oregon, USA',
  'Pennsylvania, USA',
  'Rhode Island, USA',
  'South Carolina, USA',
  'South Dakota, USA',
  'Tennessee, USA',
  'Texas, USA',
  'Utah, USA',
  'Virginia, USA',
  'Vermont, USA',
  'Washington, USA',
  'West Virginia, USA',
  'Wyoming, USA',
  'American Samoa, US Territory',
  'Guam, US Territory',
  'Nothern Mariana Islands, US Territory',
  'Puerto Rico, US Territory',
  'Virgin Islands, US Territory',
  'Alberta, Canada',
  'British Columbia, Canada',
  'Manitoba, Canada',
  'New Brunswick, Canada',
  'Newfoundland and Labrador, Canada',
  'Nova Scotia, Canada',
  'Northwest Territories, Canada',
  'Nunavut, Canada',
  'Ontario, Canada',
  'Prince Edward Island, Canada',
  'Quebec, Canada',
  'Saskatchewan, Canada',
  'Yukon, Canada',
  'Robloxia, The Metaverse',
]
